# Generated by Django 4.1.2 on 2022-10-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("identifier", models.CharField(max_length=40, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "joined_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 10, 6, 8, 7, 54, 20561),
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
